{% set version = "5.2.0" %}
{% set name = "fplll" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/fplll/fplll/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 75e17fcaa4fc5fdddbe6eb42aca5f38c4c169a4b52756e74fbe2d1769737ac9c

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('fplll', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - libtool
    - m4
  host:
    - gmp
    - mpfr
    - qd 2.3.*
  run:
    - gmp
    - mpfr
    - qd 2.3.*

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: https://github.com/fplll/fplll
  license: LGPL v2+
  license_file: {{ SRC_DIR }}/COPYING
  summary: Lattice algorithms using floating-point arithmetic
  doc_url: https://fplll.github.io/fplll
  dev_url: https://github.com/fplll/fplll

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
