# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "o0HxjFeFVivaJGwck2lfZUowGhvir/TdcgrkKLiQ1SrY6SS0Q4fpyVBjQAq+BcYtrKvA0YRdvX1NCUKtGF4YKX9gi0wmlLXrZZLnfm01P5mDFNvWtugLax5Olh8hWSw1uA2bfDEzcm/KJRorR3fQg2tGZGHLdWVEJOrfRVWVYcW9AznCzlMaDszQfREd47scS4ILFp8zjxBv2i39Nlz0lKgCzhViET34VgXU2TcmQXLCHeIIwxBmGgD+OusqQaa+Yt3DLENFMK5OYlc8qsUUpd0bxB5M9QjjG8cHrpulti7ldvnQBL9cJHR4IJjvzv67A5GqVFmxkANHtlCLBPVG4y7UmBSwQ4vB9fTG9tXr+5J+J2PG8TMP0WjNgm8DMVTmnFo1SCIXhC29MpOS+LxgX3EkL7CvlbE+S5nc2nfW9nP9N0hZygBfofDu0uRl1i/pOlGUrH4dzJrWg0TNyKW3xqwyD/JBITUrGeOvd0U2xfUopLRAzmH5L81UkWFB1wEog9Zld8ceFVK90kub5nZ41TFjd5Z17atW8mtLuICduKvurW2tRSeVdAXXq60o84XxX8XUaVrwkti/oF1vRhSfUl3p016KJtz+c9DcnaJWcTmITnTTckivdFmTyJYZVXPSp5CTG8+3Ew5bVN60ITU/JyQDDMa3Sn2T7BFJWYpKEzs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
