travis:
  secure:
    BINSTAR_TOKEN: eU+PUgacx7kbjq6DTU+9c9karD2KshAx9MKZCobBT25ADXBR8fCoScJd2J6bZkRpn9fbwkzV2GqL5ezTtwUAPxYCYiUEDXxb47+z9T3ERbJzlhpn9VQjmxaeSrOhYO5OF39FiGbM8GevIX3129OJB3LyYff9QELf8P+uVFu3P4HTWQjNNf8iJ7frNxwm78qJ4ZVEfRLEUuuPvMocNxg8jabNTJ7QRloxP6d4j/Ku7qiEcaO1orTTWJgTrzwIOqD/Ce+VFSlRUydl7ovLntjiHXayHhRjs593xHjNKu/655UJB1CIleA/0rT3Yr39v5RItK/I/8j3dJFyPyJGyatH41tK+uzgF1DBui4st+v94DzU4YekakvvTBM4TdYq2quZXFAn3aALu4efCwIU9cnPojcXwqXiiOvB5t8DaJxvCTC7cuXbLnDjRtRDUL6tVyzBYxp5GAtV1AD3Zj4pUROmFI1YE2UiOJPLOPz3kPA0nrs+89KRTt0AU5u4nTh5ZQtBux6la8GmwHZLL1DdckaJEyTFr3ifBZ6gcBB1eYPt5fTOuZW0brB8CD91HD8OIyRKrsc59vuqM5/9IUTPrnLT7f3befNnByO2Du/R1GcE/XbtXKA0bE7aWVL73I6tFxobYbh2Dc2jATZ3dbA6fSktPECz9883vWqwFZ4SVZ4jTdk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
