appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: o0HxjFeFVivaJGwck2lfZUowGhvir/TdcgrkKLiQ1SrY6SS0Q4fpyVBjQAq+BcYtrKvA0YRdvX1NCUKtGF4YKX9gi0wmlLXrZZLnfm01P5mDFNvWtugLax5Olh8hWSw1uA2bfDEzcm/KJRorR3fQg2tGZGHLdWVEJOrfRVWVYcW9AznCzlMaDszQfREd47scS4ILFp8zjxBv2i39Nlz0lKgCzhViET34VgXU2TcmQXLCHeIIwxBmGgD+OusqQaa+Yt3DLENFMK5OYlc8qsUUpd0bxB5M9QjjG8cHrpulti7ldvnQBL9cJHR4IJjvzv67A5GqVFmxkANHtlCLBPVG4y7UmBSwQ4vB9fTG9tXr+5J+J2PG8TMP0WjNgm8DMVTmnFo1SCIXhC29MpOS+LxgX3EkL7CvlbE+S5nc2nfW9nP9N0hZygBfofDu0uRl1i/pOlGUrH4dzJrWg0TNyKW3xqwyD/JBITUrGeOvd0U2xfUopLRAzmH5L81UkWFB1wEog9Zld8ceFVK90kub5nZ41TFjd5Z17atW8mtLuICduKvurW2tRSeVdAXXq60o84XxX8XUaVrwkti/oF1vRhSfUl3p016KJtz+c9DcnaJWcTmITnTTckivdFmTyJYZVXPSp5CTG8+3Ew5bVN60ITU/JyQDDMa3Sn2T7BFJWYpKEzs=}
